parameters:
    jov.form.type.category.class: Jov\Bundle\CategoryBundle\Form\Type\CategoryType

services:
    jov.form.type.category:
        class: %jov.form.type.category.class%
        arguments: [ @security.context ]
