parameters:
    jov_category.form.type.category.class: Jov\Bundle\CategoryBundle\Form\Type\CategoryType

services:
    jov_category.form.type.category:
        class: %jov_category.form.type.category.class%
        arguments: [ @security.context ]
